export const DEFAULT_SHIPPING_ZONE_CODES = {
  INSIDE_DHAKA: "INSIDE_DHAKA",
  OUTSIDE_DHAKA: "OUTSIDE_DHAKA",
} as const;

export const DEFAULT_SHIPPING_METHOD_CODES = {
  STANDARD: "STANDARD",
  EXPRESS: "EXPRESS",
} as const;
